hae_challenge/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^timetracking/', include('timetracking.urls', namespace='timetracking')),
    url(r'^admin/', include(admin.site.urls)),
)

timetracking/urls.py
from django.conf.urls import patterns, include, url
from timetracking.views import HomeView, JobsView, JobsDetailView, JobsDeleteView, TimeEntriesView, TimeEntriesDetailView, TimeEntriesDeleteView, InvoiceView

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^jobs/$', JobsView.as_view(), name='jobs'),
    url(r'^jobs/(?P<pk>\d+)/$', JobsDetailView.as_view(), name='jobs_details'),
    url(r'^jobs/(?P<pk>\d+)/invoice$', InvoiceView.as_view(), name='invoice'),
    url(r'^jobs/(?P<pk>\d+)/delete$', JobsDeleteView.as_view(), name='jobs_delete'),

    url(r'^time-entries/$', TimeEntriesView.as_view(), name='time_entries'),
    url(r'^time-entries/(?P<pk>\d+)/$', TimeEntriesDetailView.as_view(), name='time_entries_details'),
    url(r'^time-entries/(?P<pk>\d+)/delete$', TimeEntriesDeleteView.as_view(), name='time_entries_delete'),
)

timetracking/models.py
from django.db import models
from django.core import serializers
from django.core.urlresolvers import reverse
from timetracking.invoice import Invoice
import uuid


class TimeEntry(models.Model):
    time_spent = models.IntegerField(help_text="Unit is minutes.")
    entry_date = models.DateField(auto_now_add=True)
    summary = models.CharField(max_length=600)
    job = models.ForeignKey('Job', to_field='uuid')


    def get_absolute_url(self):
        return reverse('timetracking:time_entries_details', kwargs={'pk': self.pk})


    class Meta:
        verbose_name = 'Time Entry'
        verbose_name_plural = 'Time Entries'


    def __unicode__(self):
        return u"Time entry for {} on {}, {} minutes".format(self.job, self.entry_date, self.time_spent)


    def __repr__(self):
        return "<TimeEntry: {}>".format(unicode(self))


class Job(models.Model):
    uuid = models.CharField(max_length=64, unique=True, default=uuid.uuid1, editable=False)
    title = models.CharField(max_length=120)
    hourly_rate = models.DecimalField(max_digits=7, decimal_places=2)
    tax_rate = models.DecimalField(max_digits=6, decimal_places=4, help_text="Unit is %")


    def invoice(self, start_date, end_date):
        # Find time entries within the date range
        time_entries = TimeEntry.objects.filter(entry_date__range=(start_date, end_date))

        # Create an Invoice object
        new_invoice = Invoice(job=self, start_date=start_date, end_date=end_date, time_entries=time_entries)
        return new_invoice


    def get_absolute_url(self):
        return reverse('timetracking:jobs_details', kwargs={'pk': self.pk})


    def __unicode__(self):
        return unicode(self.title)


    def __repr__(self):
        return '<Job: {} - {}>'.format(self.title, self.uuid)

timetracking/views.py
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

from timetracking.models import Job, TimeEntry

import datetime


class HomeView(TemplateView):
    template_name = 'timetracking/index.html'


class AjaxableResponseMixin(object):
    """
    From Django documentation: 
    https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-editing/
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            if type(self.object) is Job:
                data = serializers.serialize('json', [self.object])[1:-1]
            else:
                data = {
                    'pk': self.object.pk,
                }
            return JsonResponse(data, safe=False)
        else:
            return response



class JobsView(AjaxableResponseMixin, CreateView):
    """
    Implement the Jobs view as a CreateView so we can create new records easily 
    on the main Jobs page. Also for all of these views, we are using the
    object's pk as an identifier because that is just the default behavior.
    We could override this with the get_object() method, and use an alternative
    identifier (like a slug or uuid) instead.

    Improvements:
    Render the page initially without the jobs and load those via ajax
    """

    template_name = 'timetracking/jobs/jobs.html'
    model = Job


    def get_context_data(self, *args, **kwargs):
        # We want to display a list of all jobs on this page, so add them to
        # the context.
        context = super(JobsView, self).get_context_data(**kwargs)
        context['jobs'] = Job.objects.all()
        return context


class JobsDetailView(AjaxableResponseMixin, UpdateView):
    template_name = 'timetracking/jobs/jobs_detail.html'
    model = Job


class JobsDeleteView(AjaxableResponseMixin, DeleteView):
    template_name = 'timetracking/jobs/jobs_delete.html'
    model = Job
    success_url = reverse_lazy('timetracking:jobs')


class TimeEntriesView(AjaxableResponseMixin, CreateView):
    template_name = 'timetracking/time_entries/time_entries.html'
    model = TimeEntry

    def get_context_data(self, *args, **kwargs):
        # We want to display a list of all time entries on this page, so add them to
        # the context.
        context = super(TimeEntriesView, self).get_context_data(**kwargs)
        context['time_entries'] = TimeEntry.objects.all()
        return context


class TimeEntriesDetailView(AjaxableResponseMixin, UpdateView):
    template_name = 'timetracking/time_entries/time_entries_detail.html'
    model = TimeEntry


class TimeEntriesDeleteView(AjaxableResponseMixin, DeleteView):
    template_name = 'timetracking/time_entries/time_entries_delete.html'
    model = TimeEntry
    success_url = reverse_lazy('timetracking:time_entries')


class InvoiceView(View):
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            # Retrieve the job we are looking at
            job_pk = kwargs.pop('pk')
            try:
                job = Job.objects.get(pk=job_pk)
            except Job.DoesNotExist as e:
                return JsonResponse({'errors': str(e)}, status=400)

            # Validate the date ranges
            # TODO: This should all be done in a Django Form
            start_date = request.POST.get('start_date')
            end_date = request.POST.get('end_date')
            date_errors = None
            try:
                date1 = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()
                date2 = datetime.datetime.strptime(end_date, '%Y-%m-%d').date()
            except Exception as e:
                date_errors = {'errors': 'Date is not correct format'}

            if date1 > date2:
                date_errors = {'errors': 'Date 1 must be less than date 2'}

            if date_errors:
                return JsonResponse(date_errors, status=400)

            # Generate and send back the invoice
            invoice = job.invoice(date1, date2)
            return JsonResponse(invoice.to_json())

        else:
            return JsonResponse({'errors': 'Request is not ajax.'}, status=400)

timetracking/templates/timetracking/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="{% static 'timetracking/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'timetracking/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'timetracking/css/skeleton.css' %}">
        <link rel="stylesheet" href="{% static 'timetracking/css/app.css' %}">
        <script src="{% static 'timetracking/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <script src="{% static 'timetracking/js/vendor/jquery-1.11.2.min.js' %}"></script>

        <!-- Add your site or application content here -->
        <div class="container">
            {% block base_content %}
            <p>Hello world! This is HTML5 Boilerplate.</p>
            {% endblock base_content %}
        </div>

        <script src="{% static 'timetracking/js/plugins.js' %}"></script>
        <script src="{% static 'timetracking/js/main.js' %}"></script>

    </body>
</html>

timetracking/templates/timetracking/index.html
{% extends 'timetracking/base.html' %}

{% block base_content %}
<h1>Home</h1>
<p>Check out some <a href="{% url 'timetracking:jobs' %}">jobs</a></p>
<p>Check out some <a href="{% url 'timetracking:time_entries' %}">time entries</a></p>
{% endblock %}

timetracking/templates/timetracking/invoices/snippets/_invoice.html
{% if invoice %}
<ul>
</ul>
{% else %}
{% endif %}

timetracking/templates/timetracking/jobs/jobs.html
{% extends 'timetracking/base.html' %}
{% load staticfiles %}


{% block base_content %}

<h1>Jobs</h1>

<div class="jobs">
    <table class="u-full-width">
        <thead>
            <tr>
                <th>ID</th>
                <th>UUID</th>
                <th>Title</th>
                <th>Hourly Rate</th>
                <th>Tax Rate</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for job in jobs %}
            <tr>
                <td><a href="{% url 'timetracking:jobs_details' pk=job.pk %}">{{ job.id }}</a></td>
                <td>{{ job.uuid }}</td>
                <td>{{ job.title }}</td>
                <td>{{ job.hourly_rate|floatformat:2 }}</td>
                <td>{{ job.tax_rate|floatformat:3 }}</td>
                <td><a href="{% url 'timetracking:jobs_delete' pk=job.pk %}" class="button">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form id="new_record_form" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit New Record" class="button" />
    </form>

    <p class="status">
    </p>

</div>


<script type="text/javascript">
$(function() {
    $form = $("#new_record_form");
    $status = $(".status");

    $form.submit(function(e) {
        e.preventDefault();
        $status.text("");
        $.ajax({
            url: "",
            type: "post",
            data: $form.serializeArray(),

            success: function(result) {
                $status.text("Success.");
                console.log(result);

                // De-serialize the JSON data and add it to the table
                var new_entry = $.parseJSON(result);
                var $tbody = $("tbody");
                var new_row = "<tr><td><a href=\"/timetracking/jobs/" + new_entry.pk + "\">" + new_entry.pk + "</a></td><td>" + new_entry.fields.uuid + "</td><td>" + new_entry.fields.title + "</td><td>" + new_entry.fields.hourly_rate + "</td><td>" + new_entry.fields.tax_rate + "</td></tr>";
                // TODO: Make sure data is HTML-escaped before appending
                $tbody.append(new_row);
            },

            error: function(result) {
                $status.text("Error: " + result.responseText);
                console.log(result);
            }
        });
    });

});

</script>

{% endblock base_content %}

timetracking/templates/timetracking/jobs/jobs_delete.html
{% extends 'timetracking/base.html' %}

{% load staticfiles %}

{% block base_content %}

<h1>Delete Job: {{ object }}</h1>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete this?</p>
    <input type="submit" value="Confirm" class="button"/>
</form>

{% endblock base_content %}

timetracking/templates/timetracking/jobs/jobs_detail.html
{% extends 'timetracking/base.html' %}
{% load staticfiles %}

{% block base_content %}

<p><a href="{% url "timetracking:jobs" %}">Jobs</a></p>

<h1>Job: {{ object }}</h1>

<div class="row">
    <form id="job_update_form" action="" method="post">{% csrf_token %}
        <h2>Update this Job</h2>
        {{ form.as_p }}
        <input type="submit" value="Update" class="button" />
    </form>

    <p id="update_status">
    </p>
</div>
<div class="row">
    <form id="invoice_form" action="{% url 'timetracking:invoice' pk=object.pk %}" method="post">{% csrf_token %}
        <h2>Create an Invoice</h2>
        <input type="date" name="start_date" />
        <input type="date" name="end_date" />
        <input type="submit" value="Generate Invoice" class="button" />
    </form>

    <p id="invoice_status">
    </p>

    <div class="invoice_result"></div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $update_form = $("#job_update_form");
    $invoice_form = $("#invoice_form");
    $update_status = $("#update_status");
    $invoice_status = $("#invoice_status");

    // Submit the form via AJAX to the current URL
    $update_form.submit(function(e) {
        e.preventDefault();
        $update_status.text("");
        $.ajax({
            url: $update_form.attr("action"),
            type: $update_form.attr("method"),
            data: $update_form.serializeArray(),

            success: function(result) {
                $update_status.text("Success.");
                console.log(result);
            },

            error: function(result) {
                $update_status.text("Error: " + result.responseText);
                console.log(result);
            }
        });
    });

    $invoice_form.submit(function(e) {
        e.preventDefault();
        $invoice_status.text("");

        $.ajax({
            url: $invoice_form.attr("action"),
            type: $invoice_form.attr("method"),
            data: $invoice_form.serializeArray(),

            success: function(result) {
                $invoice_status.text("Your invoice is below.");
                console.log(result);

                var return_html = "<ul><li>Job: " + result.job + "</li>";
                return_html += "<li>" + result.start_date + " - " + result.end_date + "</li>";
                return_html += "<li>Time Entries:</li><ul>";
                for (var i=0; i< result.time_entries.length; i++) {
                    return_html += "<li>" + result.time_entries[i] + "</li>";
                }
                return_html += "</ul>";
                return_html += "<li>Subtotal: " + result.subtotal + "</li>";
                return_html += "<li>Tax: " + result.tax + "</li>";
                return_html += "<li>Total: " + result.total + "</li>";

                $(".invoice_result").html(return_html);

            },

            error: function(result) {
                $invoice_status.text("Error: " + result.responseText);
                console.log(result);
            }
        });

    });
});
</script>

{% endblock %}

timetracking/templates/timetracking/time_entries/time_entries.html
{% extends 'timetracking/base.html' %}
{% load staticfiles %}


{% block base_content %}

<h1>Time Entries</h1>

<div class="time-entries">
    <table class="u-full-width">
        <thead>
            <tr>
                <th>ID</th>
                <th>Time Spent (minutes)</th>
                <th>Entry Date</th>
                <th>Summary</th>
                <th>Job</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in time_entries %}
            <tr>
                <td><a href="{% url 'timetracking:time_entries_details' pk=entry.pk %}">{{ entry.id }}</a></td>
                <td>{{ entry.time_spent }}</td>
                <td>{{ entry.entry_date }}</td>
                <td>{{ entry.summary|truncatechars:50 }}</td>
                <td><a href="{% url 'timetracking:jobs_details' pk=entry.job.pk %}">{{ entry.job.uuid }}</a></td>
                <td><a href="{% url 'timetracking:time_entries_delete' pk=entry.pk %}" class="button">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form id="new_record_form" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit New Record" class="button" />
    </form>

    <p class="status">
    </p>

</div>


<script type="text/javascript">
$(function() {
    $form = $("#new_record_form");
    $status = $(".status");

    $form.submit(function(e) {
        e.preventDefault();
        $status.text("");
        $.ajax({
            url: "",
            type: "post",
            data: $form.serializeArray(),

            success: function(result) {
                $status.text("Success.");
                console.log(result);
            },

            error: function(result) {
                $status.text("Error: " + result.responseText);
                console.log(result);
            }
        });
    });

});

</script>

{% endblock base_content %}

timetracking/templates/timetracking/time_entries/time_entries_delete.html
{% extends 'timetracking/base.html' %}

{% load staticfiles %}

{% block base_content %}

<h1>Delete Time Entry: {{ object }}</h1>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete this?</p>
    <input type="submit" value="Confirm" class="button"/>
</form>

{% endblock base_content %}

timetracking/templates/timetracking/time_entries/time_entries_detail.html
{% extends 'timetracking/base.html' %}
{% load staticfiles %}

{% block base_content %}

<p><a href="{% url "timetracking:time_entries" %}">Time Entries</a></p>

<h1>Time Entry: {{ object }}</h1>

<form id="time_entry_update_form" action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="button" />
</form>

<p class="status">
</p>

<script type="text/javascript">
$(document).ready(function() {
    $form = $("#time_entry_update_form");
    $status = $(".status");

    // Submit the form via AJAX to the current URL
    $form.submit(function(e) {
        e.preventDefault();
        $status.text("");
        $.ajax({
            url: "",
            type: "post",
            data: $form.serializeArray(),

            success: function(result) {
                $status.text("Success.");
                console.log(result);
            },

            error: function(result) {
                $status.text("Error: " + result.responseText);
                console.log(result);
            }
        });
    });
});
</script>

{% endblock %}